from . import department
from . import settings
from . import master_data
from . import gamification
from . import environmental
from . import social
from . import governance
from . import scoring
from . import integrations
