{
    "name": "EcoSphere ESG Management Platform",
    "summary": "Local-first ESG management, scoring, compliance, and employee participation",
    "version": "19.0.1.0.0",
    "category": "Human Resources/ESG",
    "author": "EcoSphere",
    "license": "LGPL-3",
    "depends": [
        "base",
        "web",
        "mail",
        "hr",
        "product",
        "purchase",
        "mrp",
        "fleet",
        "hr_expense",
    ],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/sequence_data.xml",
        "data/mail_templates.xml",
        "data/cron_data.xml",
        "views/menu_views.xml",
        "views/settings_views.xml",
        "views/master_data_views.xml",
        "views/environmental_views.xml",
        "views/social_views.xml",
        "views/governance_views.xml",
        "views/gamification_views.xml",
        "views/scoring_views.xml",
        "reports/esg_reports.xml",
    ],
    "demo": [
        "data/demo_data.xml",
    ],
    "application": True,
    "installable": True,
}
